[package]
name = "eth-wallet-searcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.3"
clap_derive = { version = "4.0.0-rc.1" }
wallet-gen = "0.4.1"
